### ISSUE TITLE
Car doesn't spawn

### ISSUE THREAD

**Issue by IFUNKOI** [VibR1cY/esx_gang#1]
Hello, when i want to parkout a car of a gang, the car doesn't spawn. I dont have any error. I'm on ESX legacy, before the spawn, but for now, nope. I try to put a new vGang but doesn't spawn too

**Comment by Arkalys59** [comment]
Tu aura jamais de reponse le mec (fait) un scripts il rep plus

**Comment by VibR1cY** [comment]
Ca déjà été fix hier soir
